/**
 * @household/tokens — the design tokens, the contract between design and both clients
 * (06-clients §3, design 01-foundations): a value that exists only in a design file does not
 * exist. Ported from design/v1's `foundations.js` (PL-11) and emitted three ways from one source:
 *
 * - `tokens.css`: CSS custom properties, the light palette on the root and the dark theme's
 *   changes under `[data-theme='dark']`, with the density, text-scale and motion attributes.
 *   Generated by `pnpm --filter @household/tokens css` and committed; a test fails a stale one.
 * - this module: the same tokens as a typed object, for code that needs a value rather than a
 *   custom property, and `cssVar` for code that needs the property's name.
 * - `@household/tokens/native`: a React Native theme, rem and px resolved to numbers.
 *
 * `fonts.css` declares the two faces (PL-13). `@household/tokens/primitives` holds the colour
 * ramps, which application code may not import (D-152).
 */
import { moduleFamilies } from './accent.ts'
import { fonts } from './fonts.ts'
import { themeColors } from './names.ts'
import {
  density,
  durations,
  easings,
  radii,
  reducedMotion,
  shadows,
  space,
  thresholds,
  typeScale,
} from './scale.ts'

export {
  families,
  familyAccent,
  moduleFamilies,
  moduleIds,
  type AccentToken,
  type Family,
  type ModuleId,
} from './accent.ts'
export { colors, drawnAs, sameAs, themes, type ColorToken, type Theme } from './color.ts'
export { contrast } from './contrast.ts'
export { cssVar, rules, stylesheet, type CustomProperty, type Rule } from './css.ts'
export { fonts } from './fonts.ts'
export { accentToken, colorNames, resolve, tokenOf, type ColorName } from './names.ts'
export { exempt, grounds, lateSpends, pairs, type Pair } from './pairs.ts'
export {
  baselineOf,
  density,
  durations,
  easings,
  radii,
  reducedMotion,
  remPx,
  shadows,
  space,
  tabularFigures,
  thresholds,
  typeScale,
  type Density,
  type DensityScale,
  type DurationToken,
  type EasingToken,
  type Face,
  type RadiusToken,
  type Shadow,
  type ShadowToken,
  type SpaceToken,
  type ThresholdToken,
  type TypeStep,
  type TypeToken,
} from './scale.ts'
export { statuses, type StatusToken } from './status.ts'

/**
 * The tokens as an object: every colour name resolved in each theme, and the scales as scale.ts
 * states them, px and ms as numbers and type sizes in rem.
 */
export const tokens = {
  color: { light: themeColors('light'), dark: themeColors('dark') },
  moduleFamilies,
  space,
  radii,
  shadows,
  type: typeScale,
  fonts,
  durations,
  easings,
  thresholds,
  reducedMotion,
  density,
} as const
