// The words of the controls' section of the primitives dev screen. Fixtures, in English and in
// no catalog (D-154): the section draws each through `useSample`, which accents it under the
// pseudo-locale. What a control says itself comes from the catalogs.

export const words = {
  controls: 'Controls',
  overlays: 'Overlays',
  showOut: 'Draw the controls that take nothing: out of their form, and a stepper at its bound',
  reading: 'Reading, kWh',
  readingHelp: 'As the meter in the cellar shows it.',
  readingLow: 'Lower than the last reading, 18 116.',
  readingKept: 'Last reading',
  readingOut: 'Reading of a meter that was removed',
  meter: 'Meter number',
  password: 'Password',
  passwordHelp: 'Twelve characters at the least.',
  note: 'Note',
  noteMissing: 'Say what was read, in a few words.',
  tariff: 'Tariff',
  tariffChosen: 'Tariff of the second register',
  tariffMissing: 'Choose the tariff this register is billed at.',
  tariffOut: 'Tariff of a register that was removed',
  choose: 'Choose',
  day: 'Day tariff',
  night: 'Night tariff',
  weekend: 'Weekend tariff',
  members: 'Members',
  atLeast: 'Members, at the least it holds',
  membersKept: 'Members last year',
  membersOut: 'Members of a household that was closed',
  remind: 'Remind me the day before',
  everyMeter: 'Every meter',
  shared: 'Shared with the household',
  removed: 'A choice out of its form',
  share: 'Share readings with the household',
  quiet: 'Send nothing between ten and seven',
  switchedOut: 'A switch out of its form',
  repeats: 'Repeats',
  weekly: 'Every week',
  monthly: 'Every month',
  never: 'Never',
  signOutNamed: 'Sign out Pixel 8',
  signOut: 'Sign out',
  openNamed: 'Open Dům U Lípy',
  open: 'Open',
  askDelete: 'Delete a reading',
  deleteTitle: 'Delete the March reading?',
  deleteBody: 'The reading is removed for everybody. The meter keeps its other readings.',
  keep: 'Keep it',
  deleteIt: 'Delete the reading',
  edit: 'Edit the reading',
  save: 'Save the reading',
  saved: 'March reading saved',
  deleted: 'March reading deleted',
  raise: 'Clear the checked items',
  cleared: '7 checked items cleared from Weekly shop',
  plain: 'Archive the reading',
  archived: 'March reading archived',
  rename: 'Rename the meter',
  renamed: 'Cellar meter renamed',
  remove: 'Delete the meter',
  moreFor: 'Cellar meter',
} as const

/**
 * The controls the section draws out of their form, by name, and the stepper's button that
 * stands at its bound: what its test tells the accessibility rules is disabled on purpose.
 */
export const outOfForm = [
  words.readingOut,
  words.tariffOut,
  words.membersOut,
  words.removed,
  words.switchedOut,
] as const
