// Code generated by internal/gen from docs/api/openapi.yaml. DO NOT EDIT.

package problem

// Code is the contract's ProblemCode: the stable, machine-readable discriminator
// clients switch on.
type Code string

// The members of ProblemCode, in the order the contract declares them.
const (
	CodeUnauthenticated          Code = "unauthenticated"
	CodeForbidden                Code = "forbidden"
	CodeNotFound                 Code = "not_found"
	CodeValidationFailed         Code = "validation_failed"
	CodeVersionConflict          Code = "version_conflict"
	CodeEntitlementReadOnly      Code = "entitlement_read_only"
	CodeEntitlementRestricted    Code = "entitlement_restricted"
	CodeRateLimited              Code = "rate_limited"
	CodeMethodNotAllowed         Code = "method_not_allowed"
	CodeInternal                 Code = "internal"
	CodeIdempotencyInProgress    Code = "idempotency_in_progress"
	CodeCsrfFailed               Code = "csrf_failed"
	CodeUpdateRequired           Code = "update_required"
	CodeInvalidCredentials       Code = "invalid_credentials"
	CodeRefreshTokenInvalid      Code = "refresh_token_invalid"
	CodeAccountDisabled          Code = "account_disabled"
	CodeAccountUnverified        Code = "account_unverified"
	CodeEmailTaken               Code = "email_taken"
	CodeMfaRequired              Code = "mfa_required"
	CodeMfaLocked                Code = "mfa_locked"
	CodeChildProfileLocked       Code = "child_profile_locked"
	CodeLinkRequired             Code = "link_required"
	CodeIdentityAlreadyLinked    Code = "identity_already_linked"
	CodeOnlyCredential           Code = "only_credential"
	CodeTokenExpired             Code = "token_expired"
	CodeTokenAlreadyUsed         Code = "token_already_used"
	CodeRedirectUriNotRegistered Code = "redirect_uri_not_registered"
	CodeHouseholdLimitReached    Code = "household_limit_reached"
	CodeLastOwner                Code = "last_owner"
	CodeBillingPayer             Code = "billing_payer"
	CodeAccountDeletionBlocked   Code = "account_deletion_blocked"
	CodeLayoutLocked             Code = "layout_locked"
	CodeReadOnlyParticipation    Code = "read_only_participation"
	CodeResnapshotRequired       Code = "resnapshot_required"
	CodeBatchTooLarge            Code = "batch_too_large"
	CodeNotEmpty                 Code = "not_empty"
	CodeInUse                    Code = "in_use"
	CodeDuplicateDate            Code = "duplicate_date"
	CodeDuplicateYear            Code = "duplicate_year"
	CodeAlreadyClosed            Code = "already_closed"
	CodeNotClosed                Code = "not_closed"
	CodeEditWindowClosed         Code = "edit_window_closed"
	CodeSeasonClosed             Code = "season_closed"
	CodeSlugConflict             Code = "slug_conflict"
	CodeUndeletable              Code = "undeletable"
	CodeVariantPending           Code = "variant_pending"
	CodeCatalogRule              Code = "catalog_rule"
	CodeCycle                    Code = "cycle"
	CodeInsufficientBalance      Code = "insufficient_balance"
	CodeMonotonicityViolation    Code = "monotonicity_violation"
	CodeCoverageGap              Code = "coverage_gap"
	CodePeriodOverlap            Code = "period_overlap"
	CodeNoPeriod                 Code = "no_period"
	CodeNoIncome                 Code = "no_income"
	CodeNoReferenceRate          Code = "no_reference_rate"
	CodePayloadTooLarge          Code = "payload_too_large"
	CodeUnsupportedMediaType     Code = "unsupported_media_type"
)

// Codes lists every Code, in the order the contract declares them.
var Codes = []Code{
	CodeUnauthenticated,
	CodeForbidden,
	CodeNotFound,
	CodeValidationFailed,
	CodeVersionConflict,
	CodeEntitlementReadOnly,
	CodeEntitlementRestricted,
	CodeRateLimited,
	CodeMethodNotAllowed,
	CodeInternal,
	CodeIdempotencyInProgress,
	CodeCsrfFailed,
	CodeUpdateRequired,
	CodeInvalidCredentials,
	CodeRefreshTokenInvalid,
	CodeAccountDisabled,
	CodeAccountUnverified,
	CodeEmailTaken,
	CodeMfaRequired,
	CodeMfaLocked,
	CodeChildProfileLocked,
	CodeLinkRequired,
	CodeIdentityAlreadyLinked,
	CodeOnlyCredential,
	CodeTokenExpired,
	CodeTokenAlreadyUsed,
	CodeRedirectUriNotRegistered,
	CodeHouseholdLimitReached,
	CodeLastOwner,
	CodeBillingPayer,
	CodeAccountDeletionBlocked,
	CodeLayoutLocked,
	CodeReadOnlyParticipation,
	CodeResnapshotRequired,
	CodeBatchTooLarge,
	CodeNotEmpty,
	CodeInUse,
	CodeDuplicateDate,
	CodeDuplicateYear,
	CodeAlreadyClosed,
	CodeNotClosed,
	CodeEditWindowClosed,
	CodeSeasonClosed,
	CodeSlugConflict,
	CodeUndeletable,
	CodeVariantPending,
	CodeCatalogRule,
	CodeCycle,
	CodeInsufficientBalance,
	CodeMonotonicityViolation,
	CodeCoverageGap,
	CodePeriodOverlap,
	CodeNoPeriod,
	CodeNoIncome,
	CodeNoReferenceRate,
	CodePayloadTooLarge,
	CodeUnsupportedMediaType,
}
