// Generates src/generated/messages.ts from catalogs/en.json, the source language (D-29): one
// entry per key, typed with the arguments its English message takes. It runs as the
// package's `gen` script, which turbo runs before every typecheck, so a key a client asks for
// that the catalog does not have, or an argument it leaves out, fails the type check
// (PRD 03 §9). The output is not committed: it is a function of the catalog.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { parseMessage, signature } from '../src/message.ts'

const source = new URL('../catalogs/en.json', import.meta.url)
const out = new URL('../src/generated/', import.meta.url)

const catalog: unknown = JSON.parse(readFileSync(source, 'utf8'))
if (typeof catalog !== 'object' || catalog === null || Array.isArray(catalog)) {
  throw new Error('gen: catalogs/en.json is not an object')
}

const entries = Object.entries(catalog as Record<string, unknown>)
  .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
  .map(([key, message]) => {
    if (typeof message !== 'string') throw new Error(`gen: ${key} is not a string`)
    const args = [...signature(parseMessage(message))]
      .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
      .map(([arg, kind]) => `readonly ${arg}: ${kind === 'number' ? 'number' : 'string | number'}`)
    return `  readonly ${JSON.stringify(key)}: ${args.length === 0 ? 'undefined' : `{ ${args.join('; ')} }`}`
  })

mkdirSync(out, { recursive: true })
writeFileSync(
  new URL('messages.ts', out),
  `// Generated by scripts/gen.ts from catalogs/en.json. Do not edit.

/** Every message key, with the arguments its English message takes, or undefined for none. */
export interface MessageArgs {
${entries.join('\n')}
}
`,
)
