// Generates src/generated/ from the catalogs. It runs as the package's `gen` script, which turbo
// runs before every typecheck, lint and test. The output is not committed: it is a function of
// the catalogs and of src/parts.ts.
//
// - messages.ts, from catalogs/en.json, the source language (D-29): one entry per key, typed with
//   the arguments its English message takes, so a key a client asks for that the catalog does not
//   have, or an argument it leaves out, fails the type check (PRD 03 §9).
// - parts/<locale>.<part>.json, for every language and part (src/parts.ts): that language's
//   messages whose keys are the part's, which a client that loads one language at a time fetches
//   as a file of its own (src/lazy.ts, D-159). The catalogs themselves stay whole: the server
//   reads them.
// - loaders.ts: the import of each of those files, written out.
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { locales } from '../src/locales.ts'
import { parseMessage, signature } from '../src/message.ts'
import { clientParts, deviceSegments, partOf, serverSegments } from '../src/parts.ts'

const out = new URL('../src/generated/', import.meta.url)
const partsOut = new URL('parts/', out)

const byKey = ([a]: readonly [string, unknown], [b]: readonly [string, unknown]) =>
  a < b ? -1 : a > b ? 1 : 0

/** `locale`'s catalog as it is written, its messages in the order of their keys. */
function read(locale: string): [string, string][] {
  const catalog: unknown = JSON.parse(
    readFileSync(new URL(`../catalogs/${locale}.json`, import.meta.url), 'utf8'),
  )
  if (typeof catalog !== 'object' || catalog === null || Array.isArray(catalog)) {
    throw new Error(`gen: catalogs/${locale}.json is not an object`)
  }
  return Object.entries(catalog as Record<string, unknown>)
    .sort(byKey)
    .map(([key, message]): [string, string] => {
      if (typeof message !== 'string') throw new Error(`gen: ${locale}: ${key} is not a string`)
      return [key, message]
    })
}

/** Whether `key` is in a row of the table of parts: a part's, the server's alone, or the mobile app's. */
const placed = (key: string) =>
  partOf(key) !== undefined ||
  [...serverSegments, ...deviceSegments].some((segment) => key.startsWith(`${segment}.`))

const entries = read('en').map(([key, message]) => {
  // A key in no row would be in no file a client fetches, and nothing would say so until a
  // screen asked for it.
  if (!placed(key)) {
    throw new Error(`gen: ${key} is in no part: name its first segment in src/parts.ts`)
  }
  const args = [...signature(parseMessage(message))]
    .sort(byKey)
    .map(([arg, kind]) => `readonly ${arg}: ${kind === 'number' ? 'number' : 'string | number'}`)
  return `  readonly ${JSON.stringify(key)}: ${args.length === 0 ? 'undefined' : `{ ${args.join('; ')} }`}`
})

mkdirSync(partsOut, { recursive: true })
writeFileSync(
  new URL('messages.ts', out),
  `// Generated by scripts/gen.ts from catalogs/en.json. Do not edit.

/** Every message key, with the arguments its English message takes, or undefined for none. */
export interface MessageArgs {
${entries.join('\n')}
}
`,
)

const written = new Set<string>()
for (const locale of locales) {
  const messages = read(locale)
  for (const part of clientParts) {
    const name = `${locale}.${part}.json`
    const held = Object.fromEntries(messages.filter(([key]) => partOf(key) === part))
    writeFileSync(new URL(name, partsOut), `${JSON.stringify(held, null, 2)}\n`)
    written.add(name)
  }
}
// A part taken out of the table leaves no file behind.
for (const name of readdirSync(partsOut)) {
  if (!written.has(name)) rmSync(new URL(name, partsOut))
}

writeFileSync(
  new URL('loaders.ts', out),
  `// Generated by scripts/gen.ts from src/locales.ts and src/parts.ts. Do not edit.
import type { Locale } from '../locales.ts'
import type { CatalogPart, Part } from '../parts.ts'

/**
 * Each part of each language's catalog, fetched when it is asked for. Written out, one import a
 * language and part: a bundler makes a file of each import it can read, and reads none it has to
 * compute.
 */
export const loaders: Readonly<
  Record<Locale, Readonly<Record<Part, () => Promise<{ readonly default: CatalogPart }>>>>
> = {
${locales
  .map(
    (locale) =>
      `  ${locale}: {\n${clientParts
        .map((part) => `    ${part}: () => import('./parts/${locale}.${part}.json'),`)
        .join('\n')}\n  },`,
  )
  .join('\n')}
}
`,
)
