// Package codegen renders codes_gen.go from the contract's ProblemCode enum. The generator
// writes what it renders, and a test renders it again and compares, because CI does not
// run `go generate`: without the test, a code added to openapi.yaml would stay out of the
// server until somebody happened to regenerate.
package codegen

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"regexp"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// FileName is the generated file, relative to the problem package.
const FileName = "codes_gen.go"

// member is the shape every ProblemCode value must have: it becomes a Go identifier.
var member = regexp.MustCompile(`^[a-z][a-z0-9]*(_[a-z0-9]+)*$`)

// Render returns the Go source of codes_gen.go for the OpenAPI document spec.
func Render(spec []byte) ([]byte, error) {
	doc, err := openapi3.NewLoader().LoadFromData(spec)
	if err != nil {
		return nil, fmt.Errorf("load the contract: %w", err)
	}
	ref := doc.Components.Schemas["ProblemCode"]
	if ref == nil || ref.Value == nil {
		return nil, errors.New("the contract has no components.schemas.ProblemCode")
	}
	if len(ref.Value.Enum) == 0 {
		return nil, errors.New("ProblemCode has no enum")
	}

	codes := make([]string, 0, len(ref.Value.Enum))
	seen := make(map[string]bool, len(ref.Value.Enum))
	for _, v := range ref.Value.Enum {
		code, ok := v.(string)
		if !ok || !member.MatchString(code) {
			return nil, fmt.Errorf("ProblemCode member %#v is not a snake_case string", v)
		}
		if seen[code] {
			return nil, fmt.Errorf("ProblemCode member %q is listed twice", code)
		}
		seen[code] = true
		codes = append(codes, code)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by internal/gen from docs/api/openapi.yaml. DO NOT EDIT.\n\n")
	b.WriteString("package problem\n\n")
	b.WriteString("// Code is the contract's ProblemCode: the stable, machine-readable discriminator\n")
	b.WriteString("// clients switch on.\n")
	b.WriteString("type Code string\n\n")
	b.WriteString("// The members of ProblemCode, in the order the contract declares them.\n")
	b.WriteString("const (\n")
	for _, code := range codes {
		fmt.Fprintf(&b, "\t%s Code = %q\n", Identifier(code), code)
	}
	b.WriteString(")\n\n")
	b.WriteString("// Codes lists every Code, in the order the contract declares them.\n")
	b.WriteString("var Codes = []Code{\n")
	for _, code := range codes {
		fmt.Fprintf(&b, "\t%s,\n", Identifier(code))
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format the generated source: %w", err)
	}
	return src, nil
}

// Identifier is the Go constant for a ProblemCode member: not_found becomes CodeNotFound.
func Identifier(code string) string {
	var b strings.Builder
	b.WriteString("Code")
	for part := range strings.SplitSeq(code, "_") {
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}
