// Package codegen renders iso4217_gen.go from packages/domain/src/iso4217.json, the one table
// of ISO 4217 exponents both sides compute with. The generator writes what it renders, and a
// test renders it again and compares, because CI does not run `go generate`: without the test,
// a currency added to the client's table would stay unknown to the server.
package codegen

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"maps"
	"regexp"
	"slices"
)

// Source is the table, relative to the repository root.
const Source = "packages/domain/src/iso4217.json"

// FileName is the generated file, relative to the money package.
const FileName = "iso4217_gen.go"

var code = regexp.MustCompile(`^[A-Z]{3}$`)

// Render returns the Go source of iso4217_gen.go for the table src.
func Render(src []byte) ([]byte, error) {
	var table struct {
		Published string         `json:"published"`
		Exponents map[string]int `json:"exponents"`
	}
	dec := json.NewDecoder(bytes.NewReader(src))
	if err := dec.Decode(&table); err != nil {
		return nil, fmt.Errorf("read %s: %w", Source, err)
	}
	if len(table.Exponents) == 0 {
		return nil, fmt.Errorf("%s lists no currencies", Source)
	}
	if !regexp.MustCompile(`^\d{4}-\d{2}-\d{2}$`).MatchString(table.Published) {
		return nil, errors.New("the table's published date is not YYYY-MM-DD")
	}
	codes := slices.Sorted(maps.Keys(table.Exponents))
	for _, c := range codes {
		if e := table.Exponents[c]; !code.MatchString(c) || e < 0 || e > 4 {
			return nil, fmt.Errorf("%s: %q with exponent %d is not an ISO 4217 entry", Source, c, e)
		}
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by internal/gen from %s. DO NOT EDIT.\n\n", Source)
	b.WriteString("package money\n\n")
	b.WriteString("// Published is the date of the ISO 4217 list the table was taken from.\n")
	fmt.Fprintf(&b, "const Published = %q\n\n", table.Published)
	b.WriteString("// exponents maps each ISO 4217 code to the decimal places of its minor unit.\n")
	b.WriteString("var exponents = map[string]int{\n")
	for _, c := range codes {
		fmt.Fprintf(&b, "\t%q: %d,\n", c, table.Exponents[c])
	}
	b.WriteString("}\n")

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format the generated source: %w", err)
	}
	return out, nil
}
