/* Stage 23 — the copy deck.

   Two things the module files left to the shell, both now authored per screen:

   1. TITLES in three languages. "Czech ships first" was implemented for the
      chrome — module names, the twelve state words, Help — and the 210 screens
      the module files declare stayed English. Every declared screen now carries
      a Czech and a German title, so the rail's locale switch changes the screen
      and not only the frame around it. A title that is a name — Lidl Vysočany,
      Kotel Vaillant ecoTEC, Půdorys bytu.svg — is a name in all three.
   2. LEDES in Czech, for the screens whose module file wrote an English one.
      German ledes are not authored: German is the sweep's length test, and the
      test runs on the titles and the shell chrome, which are the strings that
      sit in fixed-width chrome. HH_COPY.coverage() states that rather than
      leaving it to be assumed.
   3. The 152 STATE SENTENCES that 64 screens were short of, each in English and
      Czech. Before this file those states fell through to the shell's generic
      wording, which is the one thing 03-patterns forbids: the screen's own words
      first, the shell's only where a screen has none.

   Keyed by screen id, not by route, because a screen reached two ways is one
   screen with one set of words.
*/
(function () {
  "use strict";

  /* id: [cs, de] */
  var T = {
    "A-1": ["Přihlášení", "Anmelden"],
    "A-2": ["Založte si účet", "Konto erstellen"],
    "A-3": ["Podívejte se do e-mailu", "Sieh in dein E-Mail-Postfach"],
    "A-4": ["Pozvat někoho", "Jemanden einladen"],
    "A-5": ["Přidat druhý krok", "Zweiten Schritt hinzufügen"],
    "A-6": ["Deset kódů pro případ, že aplikaci ztratíte", "Zehn Codes, falls die App weg ist"],
    "A-7": ["Zadejte kód", "Code eingeben"],
    "A-8": ["Použít záložní kód", "Wiederherstellungscode verwenden"],
    "A-9": ["Obnovit heslo", "Passwort zurücksetzen"],
    "A-10": ["Zvolte nové heslo", "Neues Passwort wählen"],
    "A-11": ["Heslo bylo změněno", "Dein Passwort wurde geändert"],
    "A-12": ["Kde jste přihlášeni", "Wo du angemeldet bist"],
    "A-13": ["Odhlásit iPad (kuchyň)?", "iPad (Küche) abmelden?"],
    "A-14": ["Připojte se k domácnosti", "Deinem Haushalt beitreten"],
    "A-15": ["Kdo používá tenhle telefon?", "Wer benutzt dieses Telefon?"],
    "A-16": ["Ahoj Adame", "Hallo Adam"],
    "A-17": ["Přepnout profil", "Profil wechseln"],
    "A-18": ["Dáme si chvíli pauzu", "Machen wir eine kurze Pause"],
    "A-19": ["Váš účet", "Dein Konto"],
    "A-20": ["Smazat účet", "Konto löschen"],
    "A-21": ["Je čas aktualizovat", "Zeit für ein Update"],
    "A-22": ["Založte domácnost", "Haushalt einrichten"],
    "A-23": ["Pozvat Petra", "Petr einladen"],
    "A-24": ["Jana vás zve do domácnosti Tilcerovi", "Jana lädt dich zu Tilcerovi ein"],
    "A-25": ["Petr pozvánku odmítl", "Petr hat die Einladung abgelehnt"],
    "A-26": ["Opustit Tilcerovi", "Tilcerovi verlassen"],
    "A-27": ["Zachovat Tilcerovi", "Tilcerovi behalten"],
    "A-28": ["Platby", "Abrechnung"],
    "A-29": ["Jana vám nabízí převzetí plateb", "Jana bietet dir die Abrechnung an"],
    "A-30": ["Šest, které jsou pruh", "Die sechs, die Banner sind"],
    "A-31": ["Tilcerovi je uzamčená", "Tilcerovi ist gesperrt"],
    "A-32": ["Stav synchronizace", "Synchronisierungsstatus"],
    "A-33": ["Tohle by se odeslalo", "Das würde gesendet werden"],
    "A-34": ["Vaše data", "Deine Daten"],
    "A-35": ["Exportovat domácnost", "Haushalt exportieren"],
    "A-36": ["Vaše domácnosti", "Deine Haushalte"],

    "B-1": ["Nákupy", "Einkaufen"],
    "B-2": ["Nákupy", "Einkaufen"],
    "B-3": ["mléko", "Milch"],
    "B-4": ["Pořadí uliček", "Reihenfolge im Laden"],
    "B-5": ["Zásoby", "Vorräte"],
    "B-6": ["Lidl Vysočany", "Lidl Vysočany"],
    "B-7": ["Na tomhle seznamu zatím nic není", "Auf dieser Liste steht noch nichts"],
    "B-8": ["Oba dva, ve stejném obchodě", "Beide, im selben Laden"],

    "C-1": ["Domů", "Startseite"],
    "C-2": ["Přidat widget", "Widget hinzufügen"],
    "C-3": ["Uspořádat", "Anordnen"],
    "C-4": ["Výchozí rozložení domácnosti", "Die Standardansicht des Haushalts"],
    "C-5": ["Výchozí rozložení se změnilo", "Die Standardansicht hat sich geändert"],
    "C-6": ["Domů", "Startseite"],
    "C-7": ["Domů", "Startseite"],
    "C-8": ["Jeden widget se nenačetl", "Ein Widget ist fehlgeschlagen"],
    "C-9": ["Rám widgetu", "Der Widget-Rahmen"],
    "C-10": ["Všech dvacet čtyři", "Alle vierundzwanzig"],
    "C-11": ["Připomínky", "Erinnerungen"],
    "C-12": ["Nová připomínka", "Neue Erinnerung"],
    "C-13": ["O čem vás informujeme", "Worüber du informiert wirst"],
    "C-14": ["Teď ne", "Jetzt nicht"],
    "C-15": ["Dům", "Dům"],
    "C-16": ["Objednat STK", "STK-Termin buchen"],
    "C-17": ["Založit nástěnku", "Board anlegen"],
    "C-18": ["Štítky", "Labels"],
    "C-19": ["Seznam kroků", "Checkliste"],
    "C-20": ["Komentáře", "Kommentare"],
    "C-21": ["Přesunout kartu", "Karte verschieben"],
    "C-22": ["Sloupce", "Spalten"],
    "C-23": ["Poznámky", "Notizen"],
    "C-24": ["Kde je hlavní uzávěr vody", "Kde je hlavní uzávěr vody"],
    "C-25": ["Připnuté", "Angeheftet"],
    "C-26": ["Hledat v poznámkách", "Notizen durchsuchen"],
    "C-27": ["Delší verze byla přepsána", "Eine längere Fassung wurde ersetzt"],
    "C-28": ["Dokumenty", "Dokumente"],
    "C-29": ["Přidat soubor", "Datei hinzufügen"],
    "C-30": ["Pojistná inventura bytu", "Pojistná inventura bytu"],
    "C-31": ["Půdorys bytu.svg", "Půdorys bytu.svg"],
    "C-32": ["Cestovní pas — Jana", "Cestovní pas — Jana"],
    "C-33": ["6 vybráno", "6 ausgewählt"],
    "C-34": ["Co zabírají Dokumenty", "Was Dokumente belegen"],
    "C-35": ["Tohle se používá i jinde", "Das wird woanders verwendet"],
    "C-36": ["Domácí práce", "Haushaltsaufgaben"],
    "C-37": ["Tento týden", "Diese Woche"],
    "C-38": ["Všechny práce", "Alle Aufgaben"],
    "C-39": ["Vynést koš", "Müll rausbringen"],
    "C-40": ["Adamovy body", "Adams Punkte"],
    "C-41": ["Odměny", "Belohnungen"],
    "C-42": ["Ke kontrole", "Zu prüfen"],
    "C-43": ["Výměny", "Tausch"],
    "C-44": ["Je tohle ještě aktuální?", "Ist das noch eine Aufgabe?"],
    "C-45": ["Co se změnilo", "Was sich geändert hat"],
    "C-46": ["Servisní faktura Škoda", "Servisní faktura Škoda"],
    "C-47": ["Co se změnilo v řádku", "Was sich in der Zeile geändert hat"],
    "C-48": ["Zbytek historie je na serveru", "Der Rest des Protokolls liegt auf dem Server"],
    "C-49": ["Domácnost", "Haushalt"],
    "C-50": ["Členové", "Mitglieder"],
    "C-51": ["Moduly", "Module"],
    "C-52": ["Co vám domácnost oznamuje", "Worüber der Haushalt informiert"],
    "C-53": ["Co bylo odesláno", "Was gesendet wurde"],
    "C-54": ["Úložiště", "Speicher"],
    "C-55": ["Platby", "Abrechnung"],
    "C-56": ["Data", "Daten"],
    "C-57": ["Zařízení a verze", "Geräte und Versionen"],
    "C-58": ["Nastavit znovu", "Erneut einrichten"],

    "D-1": ["Za co domácnost platí?", "Wofür zahlt dieser Haushalt?"],
    "D-2": ["Jak podrobně u každé?", "Wie genau für jede?"],
    "D-3": ["Jaké schéma máte na faktuře?", "Welche Regelung steht auf deiner Rechnung?"],
    "D-4": ["Zadejte, co víte", "Gib ein, was du weißt"],
    "D-5": ["Energie a služby", "Energie und Dienste"],
    "D-6": ["Internet · O2", "Internet · O2"],
    "D-7": ["Vodoměr na zahradě", "Wasserzähler im Garten"],
    "D-8": ["Elektřina · ČEZ", "Strom · ČEZ"],
    "D-9": ["Zápis stavu měřidla", "Zählerstand eintragen"],
    "D-10": ["Stavy měřidla", "Zählerstände"],
    "D-11": ["Spotřeba", "Verbrauch"],
    "D-12": ["Opište to z faktury", "Übertrag von der Rechnung"],
    "D-13": ["Zálohy", "Abschläge"],
    "D-14": ["Vyúčtování 2025", "Abrechnung 2025"],
    "D-15": ["Chybí stav k 1. lednu 2026", "Zählerstand zum 1. Januar 2026 fehlt"],
    "D-16": ["Co za zálohu koupíte", "Was der Abschlag kauft"],
    "D-17": ["Faktury", "Rechnungen"],
    "D-18": ["Výměna měřidla", "Zählerwechsel"],
    "D-19": ["Přidat ceny", "Preise ergänzen"],
    "D-20": ["Jak to u vás s penězi chodí?", "Wie regelt ihr das Geld?"],
    "D-21": ["Kdo vydělává", "Wer verdient"],
    "D-22": ["Září 2026", "September 2026"],
    "D-23": ["Květen 2026 není zapsán", "Mai 2026 ist nicht erfasst"],
    "D-24": ["Kam letos jdou peníze", "Wohin das Geld dieses Jahr geht"],
    "D-25": ["Zaznamenat převod", "Überweisung erfassen"],
    "D-26": ["Rozdělení příjmu", "Aufteilung des Einkommens"],
    "D-27": ["Účty", "Konten"],
    "D-28": ["Transakce", "Buchungen"],
    "D-29": ["Společný výdaj", "Gemeinsame Ausgabe"],
    "D-30": ["Kdo komu", "Wer wem"],
    "D-31": ["Rozpočty", "Budgets"],
    "D-32": ["Pravidelné platby", "Laufende Zahlungen"],
    "D-33": ["Jak Netflix zdražoval", "Wie Netflix teurer wurde"],
    "D-34": ["Netflix — poslední den na výpověď", "Netflix — letzter Kündigungstag"],
    "D-35": ["Načíst výpis", "Kontoauszug einlesen"],
    "D-36": ["Není to dvakrát?", "Ist das doppelt?"],
    "D-37": ["Která částka platí?", "Welcher Betrag gilt?"],
    "D-38": ["V čem pěstujete?", "Worin baust du an?"],
    "D-39": ["Květináče", "Töpfe"],
    "D-40": ["Záhony", "Beete"],
    "D-41": ["Zahrada 2026", "Garten 2026"],
    "D-42": ["Katalog plodin", "Pflanzenkatalog"],
    "D-43": ["Vaše úpravy katalogu", "Deine Katalogänderungen"],
    "D-44": ["Výsadba", "Pflanzung"],
    "D-45": ["Práce na zahradě", "Gartenarbeit"],
    "D-46": ["Skutečnost proti plánu", "Ist gegen Plan"],
    "D-47": ["Kontrola plánu", "Planprüfung"],
    "D-48": ["Zkopírovat sezónu do 2027", "Saison nach 2027 kopieren"],
    "D-49": ["Uzavřít sezónu 2025", "Saison 2025 abschließen"],
    "D-50": ["Zásoby", "Vorräte"],
    "D-51": ["Mrazík dnes v noci", "Frost heute Nacht"],
    "D-52": ["Září 2026", "September 2026"],
    "D-53": ["Plán 2026", "Plan 2026"],
    "D-54": ["@media print", "@media print"],

    "E-1": ["Září 2026", "September 2026"],
    "E-2": ["7.–13. září", "7.–13. September"],
    "E-3": ["Středa 9. září", "Mittwoch, 9. September"],
    "E-4": ["Agenda", "Agenda"],
    "E-5": ["Událost", "Termin"],
    "E-6": ["Co máme změnit?", "Was sollen wir ändern?"],
    "E-7": ["Kdo přijde", "Wer kommt"],
    "E-8": ["Čí to je", "Wessen Termin"],
    "E-9": ["Obsazeno", "Belegt"],
    "E-10": ["Připojit kalendář", "Kalender verbinden"],
    "E-11": ["Co se přenáší", "Was übertragen wird"],
    "E-12": ["Připojené kalendáře", "Verbundene Kalender"],
    "E-13": ["Dvě verze", "Zwei Fassungen"],
    "E-14": ["Odpojit kalendář", "Kalender trennen"],
    "E-15": ["Co je v domě", "Was im Haus ist"],
    "E-16": ["Kotel Vaillant ecoTEC", "Kotel Vaillant ecoTEC"],
    "E-17": ["Servisní interval", "Wartungsintervall"],
    "E-18": ["Co už se dělalo", "Was schon gemacht wurde"],
    "E-19": ["Stav tachometru", "Kilometerstand"],
    "E-20": ["Začneme tím, co má skoro každý dům", "Fangen wir mit dem an, was fast jedes Haus hat"],
    "E-21": ["Živnostníci", "Handwerker"],
    "E-22": ["Kde jsou měřiče", "Wo die Zähler sind"],
    "E-23": ["Inventura pro pojištění", "Inventar für die Versicherung"],
    "E-24": ["Zákonné termíny", "Gesetzliche Fristen"],
    "E-25": ["Pojištění", "Versicherung"],
    "E-26": ["Tankování", "Tanken"],
    "E-27": ["Co nás to stojí", "Was es uns kostet"],
    "E-28": ["Adamovo kolo", "Adams Fahrrad"],
    "E-29": ["Zdravotní záznam", "Gesundheitsakte"],
    "E-30": ["Synulox 250 mg", "Synulox 250 mg"],
    "E-31": ["Denní režim", "Tagesablauf"],
    "E-32": ["Kartička k veterináři", "Tierarztkarte"],
    "E-33": ["Krmení a alergie", "Futter und Allergien"],
    "E-34": ["Váha", "Gewicht"],
    "E-35": ["Bela u nás už není?", "Ist Bela nicht mehr bei uns?"],
    "E-36": ["Zprávy", "Nachrichten"],
    "E-37": ["Chata — víkend", "Hütte — Wochenende"],
    "E-38": ["Přílohy", "Anhänge"],
    "E-39": ["Klára přišla včera", "Klára ist gestern dazugekommen"],
    "E-40": ["Co Zprávy zabírají", "Was Nachrichten belegen"],
    "E-41": ["Ztlumit", "Stummschalten"],
    "E-42": ["Hledání", "Suche"],

    "F-1": ["Hledání v celé domácnosti", "Globale Suche"],
    "F-2": ["Řádek výsledku — bez úryvku / bez cesty", "Ergebniszeile — ohne Auszug / ohne Pfad"],
    "F-3": ["Dnes", "Heute"],
    "F-4": ["Panel Přidat", "Hinzufügen-Blatt"],
    "F-5": ["Konflikty", "Konflikte"],
    "F-6": ["Vyúčtování elektřiny za březen", "Stromabrechnung März"],
    "F-7": ["Změny, které server odmítl", "Vom Server abgelehnte Änderungen"],
    "F-15": ["Uspořádat moduly", "Module anordnen"],
    "F-16": ["Otevírání odkazu", "Link wird geöffnet"],
    "F-17": ["Není k dispozici", "Nicht verfügbar"],
    "F-18": ["Poznámka byla přejmenována", "Die Notiz wurde umbenannt"],
    "F-19": ["Nápověda — model a tři povrchy", "Hilfe — Modell und drei Oberflächen"],
    "F-20": ["Oznámení", "Benachrichtigungen"]
  };

  /* Czech ledes, for the screens whose module file wrote an English one. */
  var L = {
    "A-1": "Jeden účet, ať jste v kolika domácnostech chcete.",
    "A-2": "Domácnost můžete založit hned potom, nebo se připojit k té, kam vás pozvali.",
    "A-3": "Poslali jsme odkaz na jana@tilcerovi.cz. Platí 24 hodin.",
    "A-5": "Šestimístný kód z ověřovací aplikace, navíc k heslu.",
    "A-6": "Každý funguje jednou. Uložte si je jinam než do tohoto telefonu.",
    "A-7": "Z tohoto zařízení jste se ještě nepřihlásili.",
    "A-8": "Jeden z deseti, které jste si uložili při zapnutí druhého kroku.",
    "A-9": "Pošleme e-mailem odkaz, kterým nastavíte nové.",
    "A-11": "8. září ve 21:14 · Praha, Česko · Chrome na Windows.",
    "A-14": "Napište šest znaků z kódu, který jste dostali.",
    "A-16": "Zadejte PIN.",
    "A-17": "iPad v kuchyni · Tilcerovi",
    "A-20": "O vašem účtu platí čtyři věci. Dvě z nich je potřeba vyřešit nejdřív.",
    "A-22": "Čtyři z těchto pěti čteme z tohoto telefonu. Kteroukoli změňte.",
    "A-23": "Sedmnáct rozhodnutí, už zodpovězených. Změňte ta, která chcete.",
    "A-24": "Tady je přesně to, co vám to dává.",
    "A-25": "9. září v 18:20.",
    "A-26": "Dvě věci je potřeba vyřešit nejdřív, a obě jsou tady.",
    "A-27": "Jedna cena za celou domácnost, ať je vás kolik chce.",
    "A-29": "Tilcerovi · nabídnuto 9. září v 19:04.",
    "A-30": "Dva z osmi stavů nejsou pruh vůbec.",
    "A-32": "Čtyři zařízení a co každé z nich opravdu má.",
    "A-33": "Dokud nestisknete odeslat, nic neodejde.",
    "A-34": "Šest práv, a každé je tlačítko.",
    "A-35": "Všechno, jako soubory, které fungují i bez nás.",
    "A-36": "Ve které domácnosti jste, je v adrese, ne v přihlášení — proto je to napsané tady, ne zapamatované.",

    "B-1": "Čtyři seznamy. Na jeden z nich odkládá rychlé přidávání.",
    "B-3": "Devět polí. Jedno je povinné a to už jste napsali.",
    "B-4": "Přetáhněte uličky do pořadí, ve kterém jimi opravdu chodíte.",
    "B-5": "Devět týdnů vlastní historie téhle domácnosti, seřazených.",
    "B-6": "9. září · jedenáct položek odškrtnuto · tři z nich s cenou.",
    "B-8": "Šest operací, dva telefony, žádný signál a nic k řešení.",

    "C-1": "Devět uložených položek, jedna z nich klíč, který tahle verze neumí.",
    "C-2": "Jen to, na co má tenhle člen oprávnění, seskupené po modulech.",
    "C-3": "Pořadí a velikost. Obojí se ukládá jednou na widget a jde s vámi na každé zařízení.",
    "C-4": "Co uvidí nový člen jako první, ještě než si cokoli vybral.",
    "C-6": "Vlastník nastavil čtyři widgety. Adam je pak může přesunout, zvětšit nebo přidat vlastní.",
    "C-7": "Stejné čtyři widgety a žádná možnost je přeskládat — chybí, nejsou zakázané.",
    "C-9": "Jeden rám, tři velikosti, dvanáct stavů a vlastní obnovení.",
    "C-10": "Každý klíč ve výchozí velikosti a s řádkem modulu, odkud pochází.",
    "C-11": "Všechno, co odebíráte, ze všech modulů, po termínu nahoře.",
    "C-12": "Den, název a — pokud se opakuje — pravidlo.",
    "C-13": "Podle druhu: jak dlouho dopředu a kudy se to k vám dostane.",
    "C-14": "Přestaňte to dostávat, aniž byste všem oznámili, že je hotovo.",
    "C-15": "Sloupce napříč, karty dolů, a pořadí si určuje domácnost.",
    "C-16": "Všechno o jedné kartě na jedné obrazovce, s nástěnkou pořád za ní.",
    "C-17": "Čtyři tvary a jeden prázdný. Žádný z nich nepřináší obsah.",
    "C-18": "Na nástěnku, pojmenované, barevné — a název je vidět vždycky.",
    "C-19": "Seřazené položky s příznakem hotovo a průběh na čele karty.",
    "C-20": "Prostý text, vlákno u karty, se zmínkami — rozhovor, který by jinak byl ve Zprávách.",
    "C-21": "Nástěnka, pak sloupec. Karta si nechává id, komentáře i historii.",
    "C-22": "Pojmenujte ho, seřaďte ho a řekněte, co se v něm děje.",
    "C-23": "Jeden strom na kořen. Přepínač mění, ve kterém stromu jste.",
    "C-24": "Ukládá se Markdown. Ukazuje se WYSIWYG.",
    "C-25": "Pro všechny, nebo jen pro mě.",
    "C-26": "Název a text, v jazyce té poznámky.",
    "C-27": "Tady je — ne: kterou jste chtěli?",
    "C-28": "Složky, kořeny a cesty — stejný strom jako u Poznámek, jen nad soubory.",
    "C-29": "Vyfoťte to, nebo vyberte. Řádek existuje dřív než data.",
    "C-30": "Jeden soubor, čtyři koncové body a trvalý odkaz.",
    "C-31": "Tenhle se tady nikdy nevykresluje.",
    "C-32": "Typ a datum udělají ze šanonu něco, co vám samo řekne.",
    "C-33": "Domácnost, která se stěhuje ze složky v notebooku, nahraje dvě stě souborů a potřebuje je roztřídit.",
    "C-34": "Největší položka účtu, po jednotlivých souborech.",
    "C-35": "Pojmenované, ne zakázané.",
    "C-36": "Moje, pak co je volné, pak to, na čem je někdo jiný.",
    "C-37": "Členové napříč, dny dolů.",
    "C-38": "Definice, ne jednotlivé výskyty.",
    "C-39": "Čtyři druhy rozvrhu, čtyři způsoby přidělení.",
    "C-40": "Každý řádek říká kdo a proč.",
    "C-41": "Určuje si je domácnost a s penězi nemají nic společného.",
    "C-42": "Jedna práce v téhle domácnosti čeká na kontrolu.",
    "C-43": "Poproste někoho, ať se vystřídá.",
    "C-44": "Po termínu 51 dní a nikdo se jí nedotkl.",
    "C-45": "Kdo co změnil, kdy a odkud.",
    "C-46": "Všechno, co kdy s tímhle souborem bylo, od nejstaršího.",
    "C-47": "Stará hodnota, nová hodnota, jedno pole na řádek.",
    "C-48": "Jediná obrazovka, která to říká rovnou.",
    "C-50": "Přístup všech, viditelný všem.",
    "C-51": "Zapnuto pro celou domácnost, nebo vypnuto pro celou domácnost.",
    "C-52": "Vyberte, co se stane. Pravidlo se napíše za vás.",
    "C-53": "Každý pokus, s výsledkem a důvodem.",
    "C-56": "Export, omezení, předání, smazání. V tomhle pořadí.",
    "C-57": "Užitečné, když jeden člověk vidí něco, co ostatní ne.",
    "C-58": "Vlastní nastavení modulu, dostupné i po prvním spuštění.",

    "D-1": "Vyberte, co máte. Další se dá přidat později.",
    "D-2": "Tři odpovědi, a jeden modul zvládne všechny tři.",
    "D-3": "Vyberte to, co sedí, a formulář vyjde slovy vaší faktury.",
    "D-4": "Všechno je nepovinné. Modul funguje s tím, co máte.",
    "D-5": "Zůstatek tam, kde se dá spočítat, a rezerva tam, kde ne.",
    "D-6": "Faktury, útrata a kde se změnila cena. Žádný měřič, tarif ani odhad.",
    "D-7": "Stavy a spotřeba. Žádné ceny, protože tenhle měřič nikdo nefakturuje.",
    "D-8": "Stavy, ceny, zálohy, období a vyúčtování.",
    "D-9": "Dva registry, pět číslic a jedno desetinné místo, a fotka, když je špatně vidět.",
    "D-10": "Každý stav s tím, odkud je, a co který úsek spotřeboval.",
    "D-11": "Po úsecích, s odhadovaným sloupcem vykresleným a vyřazeným.",
    "D-12": "Jeden řádek tady na jeden řádek faktury, v pořadí, ve kterém je vytištěná.",
    "D-13": "Rozpis a každý měsíc s tím, co se s ním doopravdy stalo.",
    "D-14": "Spočítané proti fakturovanému, v penězích i v jednotkách.",
    "D-15": "Ten den se změnila cena a ke stejnému dni se dělí rok, takže obojí potřebuje stav měřidla.",
    "D-16": "Vaše záloha, bez pevné části, v kilowatthodinách.",
    "D-17": "Co jste zaplatili, kdy, a kde se to změnilo.",
    "D-18": "Starý uzavřete posledním stavem, nový otevřete prvním.",
    "D-19": "Co přechod přidá a co nechá přesně tak, jak to je.",
    "D-20": "Čtyři odpovědi. Každá zapne své funkce a předvyplní tvar, který jde změnit.",
    "D-21": "Lidé a příjmy, účty, plán rozdělení s živým příkladem, kategorie.",
    "D-22": "Co přišlo, co s tím plán udělá a co zbývá.",
    "D-23": "Skutečný problém není špatné číslo. Je to měsíc, který nikdo nezapsal.",
    "D-24": "Příjem, co si kdo nechá, co dojde na společný účet, co z něj odejde a co zůstane.",
    "D-25": "Jedno ťuknutí, plánovaná částka předvyplněná, datum dnes a částka upravitelná, protože banky zaokrouhlují.",
    "D-26": "Seřazená pravidla a pod nimi příklad na skutečných číslech tohoto měsíce.",
    "D-27": "Libovolný počet, šest typů. Osobní účet má vlastníka; žádný jiný typ ho mít nesmí.",
    "D-28": "Jedna tabulka pode vším: výdaje, importy, rozdělení, zaúčtované pohyby a potvrzená předplatná.",
    "D-29": "Kdo platil, pro koho to je a jak se to dělí — a dělení je vidět dřív, než se uloží.",
    "D-30": "Čistá částka na člověka, seznam po dvojicích a nejkratší sada plateb, která to celé vyrovná.",
    "D-31": "Plán, skutečnost, zbytek a kam měsíc tímhle tempem míří.",
    "D-32": "Co přijde, co to stojí a co se ještě dá vypovědět.",
    "D-33": "Každá potvrzená změna, s tím, kdo ji potvrdil a kdy.",
    "D-34": "Ozve se ve výpovědní lhůtě, ne při obnovení, protože jen tehdy to má cenu.",
    "D-35": "Nahrajte, podívejte se na první řádky, řekněte, který sloupec je co, a uložte to pod názvem.",
    "D-36": "Pět řádků vypadá jako něco, co tu už je. Čtyři z nich opravdu jsou, protože se dva výpisy týden překrývají.",
    "D-37": "Dvě hodnoty, dva lidé, dva časy — a pole pro třetí odpověď.",
    "D-38": "Tři odpovědi a ta, kterou vyberete, určí úroveň. Pak kde, co pěstujete a kolik máte místa.",
    "D-39": "Nádoby, co je v nich a kdy se naposled zalévalo.",
    "D-40": "Čtrnáct záhonů ve třech zónách, v pořadí, jak stojí, a co je v nich teď.",
    "D-41": "Sezóna, kontrola plánu, co po čem následovalo, a záznam zásob.",
    "D-42": "Asi tři sta plodin v pěti jazycích, s termíny přepočtenými na vaše mrazy.",
    "D-43": "Vaše vlastní plodiny a odrůdy a každé pole katalogu, které jste pro tuhle domácnost změnili.",
    "D-44": "Záhon, plodina, odrůda, kolik, pět plánovaných dat a čtyři skutečná.",
    "D-45": "Co z výsadby vyplývá, po termínu nahoře, po týdnech, a mezi tím vaše vlastní úkoly.",
    "D-46": "Sázeli jste třináct dní po plánu. Plán se nepohnul.",
    "D-47": "Jedenáct kontrol nad plánem téhle sezóny. Vždycky jen doporučení — nic tady nebrání uložení.",
    "D-48": "Celá příští sezóna a její kontrola, ještě než vznikne.",
    "D-49": "Konečné výnosy, co se nepovedlo, a mrazy, které jste opravdu zažili.",
    "D-50": "Co se zavařilo, jak, a kolik zbývá.",
    "D-51": "Jedno varování, teplota a rostliny, o které jde.",
    "D-52": "Převedené, pak blok na každý týden, pak co je ke sklizni. Skutečná zaškrtávátka.",
    "D-53": "Čtrnáct záhonů dolů, dvanáct měsíců napříč, v pořadí zón.",
    "D-54": "Deset pravidel, a každé z nich je rozhodnutí o jiném médiu.",

    "E-1": "Pět řádků po sedmi, od pondělí, s barvou člena na každém řádku.",
    "E-2": "Sedm sloupců proti časové ose. Dvě věci najednou jsou dva boxy vedle sebe.",
    "E-3": "Jeden sloupec, plný detail, a jediný pohled, kde čtyřhodinové okno vypadá na čtyři hodiny.",
    "E-4": "Dny, ve kterých něco je, popořadě, a ty prázdné se přeskakují.",
    "E-5": "Název, kdy, kde, kdo, opakování, připomínky. V tomhle pořadí, a opakování je věta.",
    "E-6": "Tři možnosti a každá říká, kolika termínů se dotkne.",
    "E-7": "Kdo tam je, kdo odpověděl a koho se nikdo neptal.",
    "E-8": "Pět členů, pět barev a filtr, který zůstává v tomhle zařízení.",
    "E-9": "Interval, ve kterém něco je a nedá se to otevřít.",
    "E-10": "Čtyři poskytovatelé a jedna věta, která pojmenuje účet dřív, než se cokoli připojí.",
    "E-11": "Dvě nastavení na kalendář, ne na účet: kterým směrem a kolik.",
    "E-12": "Čtyři připojení, kdy každé naposled fungovalo a jak staré je to, na co se díváte.",
    "E-13": "Obě hodnoty, oba autoři, oba časy — a ta, která prohraje, se uchová.",
    "E-14": "A co se má stát s tím, co přineslo.",
    "E-15": "Jedno tělo seznamu, tři slovníky, a slovo pro tu věc si určuje modul.",
    "E-16": "Co to je, kdy měl servis, co je v záruce, kde je návod, co to stálo.",
    "E-17": "Každých 12 měsíců nebo 15 000 km, podle toho, co nastane dřív — a obrazovka říká, které z toho vyhrálo.",
    "E-18": "S datem, kým, za kolik, a s fakturou u toho.",
    "E-19": "Jedna neklesající řada v tisícinách jednotky, sdílená s knihou tankování.",
    "E-20": "Pět běžných věcí pro vaši zemi, každá s obvyklým intervalem, na jedno ťuknutí.",
    "E-21": "Jméno, číslo a co dělali. Pět polí a žádné šesté.",
    "E-22": "Kde je uzávěr, s fotkou a s tím, jak se k němu dostat.",
    "E-23": "Fotky, výrobní čísla, data nákupu, hodnoty. Na papíře, protože ten den je to potřeba.",
    "E-24": "STK 5. října, z jedné první registrace a profilu země.",
    "E-25": "Připomínka obnovení se ozve ve výpovědní lhůtě, ne při vypršení, aby se ještě dalo přejít jinam.",
    "E-26": "Sedm záznamů, tři z nich do plna, a spotřeba počítaná mezi plnými.",
    "E-27": "Šest řádků, každý měřený přes období, které obrazovka pojmenuje.",
    "E-28": "Stejný editor s jinou sadou polí a bez zašedlé kolonky na značku.",
    "E-29": "Šest druhů záznamu na jedné datované ose — to, co nemůžete najít, když se veterinář zeptá.",
    "E-30": "Dvacet dávek za deset dní, odškrtává ten, kdo je dal.",
    "E-31": "Sedm věcí u dvou zvířat, resetuje se o půlnoci, ukazuje kdo a kdy.",
    "E-32": "Ordinace, veterinář a pohotovostní číslo na jedno ťuknutí shora.",
    "E-33": "Co, kolik, jak často a co nesmí.",
    "E-34": "Pět vážení za rok proti cílovému rozmezí podle druhu.",
    "E-35": "Dvě možnosti, datum, a nic smazaného.",
    "E-36": "Tři konverzace, nepřečtené nahoře, a jeden řádek o tom, kdo tu není.",
    "E-37": "Sedm zpráv, reakce jako štítky, dva soubory u jedné a náhrobek tam, kde jedna byla smazána.",
    "E-38": "Čtyři soubory ve třech stavech, a řádek existuje dřív než data.",
    "E-39": "Čtyři z dvanácti zpráv, na obou cestách doručení, a počet nepřečtených tím omezený.",
    "E-40": "Největší, nejstarší a součet na konverzaci — a přesun do Dokumentů vedle mazání.",
    "E-41": "Jeden přepínač na konverzaci, ctí noční klid i kategorii přímých zpráv.",

    "F-5": "Všechno, co čeká na odpověď, na jednom místě a ve vašem čase. Nic se tu nevyřeší samo a nic nevyprší.",
    "F-6": "Vy jste zadali 450. Petr v 18:40 zadal 500. Co platí?",
    "F-7": "V praxi se stávají čtyři důvody. Každý pojmenuje, co se stalo, a nabídne zkusit znovu, upravit a zahodit.",
    "F-15": "Vaše pořadí, vaše připnutí, vaše skrytá sekce. Na člena a na domácnost, a stačí k tomu oprávnění číst.",
    "F-16": "Když přijde odkaz, můžou platit čtyři věci, a každá dostane hotovou obrazovku místo kolečka.",
    "F-17": "Tohle není k dispozici.",
    "F-18": "Adresa se změnila. Nic se nepřesměrovává.",
    "F-20": "Oprávnění telefonu a vaše čtyři kategorie, na jedné obrazovce."
  };
  /* The 152 state sentences 64 screens were short of: id → state → [en, cs].
     An empty state is a triple — one sentence, one example, one action — in both. */
  var SS = {
    "A-12": { pending: ["Signing this device out is queued here and reaches the other sessions when you are back online.",
      "Odhlášení čeká na tomhle zařízení a k ostatním přihlášením dorazí, až budete online."] },
    "A-15": { error: ["We could not read the profiles on this device. Nobody has been signed out — try again.",
      "Profily na tomhle zařízení se nepodařilo načíst. Nikdo není odhlášen, zkuste to znovu."] },
    "A-17": { error: ["Switching profiles failed. You are still on the profile you started from.",
      "Přepnutí profilu se nepovedlo. Pořád jste na profilu, ze kterého jste vyšli."] },
    "A-19": { pending: ["Your changes are saved on this device and go up the moment there is a connection.",
      "Změny jsou uložené v zařízení a odejdou, jakmile bude připojení."] },
    "A-23": {
      empty: [["No modules are shared with Petr yet.", "Shopping is where most households start — everybody uses it.", "Grant a module"],
              ["S Petrem zatím nesdílíte žádný modul.", "Většina domácností začíná Nákupy — ty používá každý.", "Udělit modul"]],
      absent: ["Inviting people is the owner's to do, so this screen is not part of your app.",
        "Zvát lidi může vlastník, takže tuhle obrazovku ve své aplikaci nemáte."],
      withdrawn: ["You could invite people until 9 September. The invitation you were writing is kept as a draft.",
        "Zvát lidi jste mohli do 9. září. Rozepsaná pozvánka zůstává jako koncept."]
    },
    "A-28": { empty: [["No invoices yet.", "The first one arrives the day after the household subscribes.", "See what is included"],
      ["Zatím žádné faktury.", "První přijde den po objednání předplatného.", "Co je v ceně"]] },
    "A-32": {
      empty: [["Nothing has synced yet.", "A device that has never been online has no queue and no history to show.", "Check again"],
              ["Zatím se nic nesynchronizovalo.", "Zařízení, které ještě nebylo online, nemá frontu ani historii.", "Zkusit znovu"]],
      pending: ["Two changes are still queued, so this page is one refresh behind the household.",
        "Dvě změny ještě čekají ve frontě, takže tahle stránka je o jedno obnovení pozadu."],
      absent: ["Sync health is the owner's screen. Your own device shows its state in the app bar.",
        "Stav synchronizace vidí vlastník. Své zařízení poznáte podle pruhu nahoře."]
    },
    "A-34": { absent: ["Your data rights sit on your account rather than in this household, so they are not shown here.",
      "Práva k vašim datům jsou u účtu, ne u téhle domácnosti, takže tady nejsou."] },
    "A-35": {
      empty: [["There is nothing to export yet.", "A household with no modules set up produces an empty archive.", "Set up a module"],
              ["Zatím není co exportovat.", "Domácnost bez nastavených modulů vyexportuje prázdný archiv.", "Nastavit modul"]],
      absent: ["Exporting the household is the owner's to do, so this screen is not part of your app.",
        "Export domácnosti dělá vlastník, takže tuhle obrazovku ve své aplikaci nemáte."]
    },
    "A-36": {
      absent: ["You are in one household, so there is nothing to switch between.",
        "Jste v jedné domácnosti, takže není mezi čím přepínat."],
      withdrawn: ["Tilcerovi is no longer yours to open. The households you are still in are listed above.",
        "Tilcerovi už neotevřete. Domácnosti, ve kterých zůstáváte, jsou výše."]
    },

    "B-1": {
      empty: [["No lists yet.", "Most households start with one called Shopping and add a second for the drugstore.", "Make a list"],
              ["Zatím žádné seznamy.", "Většina domácností začne jedním – Nákupy – a druhý přidá na drogerii.", "Vytvořit seznam"]],
      pending: ["Two lists were made on this phone and are waiting to go up. Both work now.",
        "Dva seznamy vznikly na tomhle telefonu a čekají na odeslání. Oba fungují už teď."],
      conflicted: ["One list was renamed in two places. Both names are kept until you pick one.",
        "Jeden seznam dostal dvě jména. Obě zůstávají, dokud si jedno nevyberete."],
      rejected: ["The list was not made: that name is already used in this household.",
        "Seznam nevznikl: takové jméno už v domácnosti je."],
      absent: ["Shopping is not one of your modules, so there is nothing here to open.",
        "Nákupy mezi vašimi moduly nejsou, takže tu není co otevřít."],
      withdrawn: ["Shopping was shared with you until 9 September. The lists stayed with the household.",
        "Nákupy s vámi byly sdílené do 9. září. Seznamy zůstaly domácnosti."]
    },
    "B-2": {
      empty: [["Nothing on this list yet.", "Type “2 rohlíky, mléko, máslo” and it becomes three items.", "Add the first item"],
              ["Na seznamu zatím nic není.", "Napište „2 rohlíky, mléko, máslo“ a vzniknou tři položky.", "Přidat první položku"]],
      pending: ["What you tick in the shop is kept here and goes up when there is signal again.",
        "Co v obchodě odškrtnete, zůstává tady a odejde, až bude zase signál."],
      rejected: ["Somebody deleted this list while you were in it. What you added is kept below.",
        "Někdo seznam mezitím smazal. Co jste přidali, zůstává níže."],
      absent: ["This list belongs to a module you do not hold, so it is not part of your app.",
        "Tenhle seznam patří k modulu, který nemáte, takže ho ve své aplikaci nenajdete."],
      withdrawn: ["This list was shared with you until 9 September. Nothing you ticked was undone.",
        "Tenhle seznam s vámi byl sdílený do 9. září. Nic z toho, co jste odškrtli, se nevrátilo."],
      readonly: ["The household is read-only, so the list can be read and walked but not ticked.",
        "Domácnost je jen pro čtení, takže seznam přečtete a projdete, ale neodškrtnete."]
    },
    "B-3": {
      empty: [["This item has nothing filled in but its name.", "A quantity and a note are usually enough — “2 l, ta velká krabice”.", "Add a quantity"],
              ["U téhle položky není nic než název.", "Většinou stačí množství a poznámka — „2 l, ta velká krabice“.", "Doplnit množství"]],
      pending: ["The edit is saved on this phone. The list already shows it to you and to nobody else yet.",
        "Úprava je uložená v telefonu. Na seznamu ji zatím vidíte jen vy."],
      rejected: ["The item was removed from the list before this edit arrived, so it was not applied.",
        "Položka zmizela ze seznamu dřív, než úprava dorazila, takže se nepoužila."],
      absent: ["Item detail belongs to Shopping, which is not one of your modules.",
        "Detail položky patří k Nákupům, a ty mezi vašimi moduly nejsou."],
      withdrawn: ["Shopping was shared with you until 9 September, so this item no longer opens.",
        "Nákupy s vámi byly sdílené do 9. září, takže se tahle položka už neotevře."],
      readonly: ["The household is read-only. Every field is readable and none of them is editable.",
        "Domácnost je jen pro čtení. Všechna pole si přečtete, žádné neupravíte."]
    },
    "B-4": {
      empty: [["No walking order yet.", "Set it once for Lidl Vysočany and every trip there follows it.", "Set the order"],
              ["Pořadí uliček zatím není.", "Nastavte ho jednou pro Lidl Vysočany a každý nákup ho pak drží.", "Nastavit pořadí"]],
      pending: ["The new order is on this phone. The next person in the shop gets it once you are online.",
        "Nové pořadí je v tomhle telefonu. Další, kdo půjde nakupovat, ho dostane, až budete online."],
      rejected: ["The order was not saved: a category in it no longer exists in the household's shop.",
        "Pořadí se neuložilo: jedna kategorie v něm už v obchodě domácnosti není."],
      withdrawn: ["Shopping was shared with you until 9 September. The order you set stayed with the household.",
        "Nákupy s vámi byly sdílené do 9. září. Pořadí, které jste nastavili, zůstalo domácnosti."],
      readonly: ["The household is read-only, so the order is shown as it stands and cannot be dragged.",
        "Domácnost je jen pro čtení, takže pořadí vidíte, ale přetáhnout ho nejde."]
    },
    "B-5": {
      empty: [["No staples yet.", "Nine weeks of buying milk every Tuesday is what turns it into one.", "See how staples work"],
              ["Zatím žádné zásoby.", "Devět týdnů kupovaného mléka každé úterý z něj udělá zásobu.", "Jak zásoby fungují"]],
      pending: ["The threshold you changed is saved here and reaches the household with the next sync.",
        "Změněná hranice je uložená tady a k domácnosti se dostane při příští synchronizaci."],
      rejected: ["The staple was not saved: its item was deleted from the household's catalog.",
        "Zásoba se neuložila: její položka byla z katalogu domácnosti smazána."],
      absent: ["Staples belong to Shopping, which is not one of your modules.",
        "Zásoby patří k Nákupům, a ty mezi vašimi moduly nejsou."],
      withdrawn: ["Shopping was shared with you until 9 September. The household's staples are unchanged.",
        "Nákupy s vámi byly sdílené do 9. září. Zásoby domácnosti zůstaly beze změny."],
      readonly: ["The household is read-only, so thresholds are shown and cannot be moved.",
        "Domácnost je jen pro čtení, takže hranice vidíte, ale neposunete."]
    },
    "B-6": {
      empty: [["Nothing was cleared on this trip.", "Tick something in the shop and it appears here with what it cost.", "Open the list"],
              ["Na tomhle nákupu se nic neodškrtlo.", "Odškrtněte něco v obchodě a objeví se to tady i s cenou.", "Otevřít seznam"]],
      pending: ["The trip is finished on this phone. It reaches Finance when there is signal.",
        "Nákup je v tomhle telefonu uzavřený. Do Financí se dostane, až bude signál."],
      absent: ["Trip summaries belong to Shopping, which is not one of your modules.",
        "Souhrn nákupu patří k Nákupům, a ty mezi vašimi moduly nejsou."],
      withdrawn: ["Shopping was shared with you until 9 September. The trip stayed in the household's history.",
        "Nákupy s vámi byly sdílené do 9. září. Nákup zůstal v historii domácnosti."],
      readonly: ["The household is read-only, so the trip is readable and the Finance offer is not available.",
        "Domácnost je jen pro čtení, takže nákup si přečtete, ale nabídku do Financí nevyužijete."]
    },

    "C-1": {
      empty: [["Your home screen has no widgets on it.", "Most households start with today's chores and the shopping list.", "Add a widget"],
              ["Na ploše nemáte žádný widget.", "Většina domácností začíná dnešními pracemi a nákupním seznamem.", "Přidat widget"]],
      rejected: ["The layout was not saved: one widget in it needs a module you no longer hold.",
        "Rozložení se neuložilo: jeden widget v něm potřebuje modul, který už nemáte."],
      absent: ["Every widget you had needed a module that is no longer yours, so the screen offers to fill itself.",
        "Každý widget, který jste měli, potřeboval modul, který už nemáte, takže se plocha nabízí zaplnit."],
      withdrawn: ["Two widgets left with the modules that were withdrawn. The rest of your layout is untouched.",
        "Dva widgety odešly s odebranými moduly. Zbytek rozložení zůstal."],
      readonly: ["The household is read-only. The widgets read; their buttons are not there to press.",
        "Domácnost je jen pro čtení. Widgety se čtou, jejich tlačítka tu nejsou."]
    },
    "C-2": {
      empty: [["Nothing to add yet.", "A widget appears here as soon as its module is on for the household.", "Turn on a module"],
              ["Zatím není co přidat.", "Widget se tu objeví, jakmile je jeho modul v domácnosti zapnutý.", "Zapnout modul"]],
      pending: ["The widget is on your home screen already and reaches your other devices at the next sync.",
        "Widget už na ploše máte; na další zařízení dorazí při příští synchronizaci."],
      rejected: ["The widget was not added: its module was turned off while the catalog was open.",
        "Widget se nepřidal: jeho modul byl mezitím vypnutý."],
      withdrawn: ["Four entries left the catalog with the modules that were withdrawn.",
        "Čtyři položky z katalogu odešly spolu s odebranými moduly."],
      readonly: ["The household is read-only, so the catalog is browsable and nothing can be added.",
        "Domácnost je jen pro čtení, takže katalog projdete, ale nic nepřidáte."]
    },
    "C-3": {
      empty: [["Nothing to arrange yet.", "Add a widget first and this screen becomes the place you order them.", "Add a widget"],
              ["Zatím není co uspořádat.", "Nejdřív přidejte widget a tahle obrazovka bude místo, kde se řadí.", "Přidat widget"]],
      pending: ["The new order is on this device and follows you to the others once you are online.",
        "Nové pořadí je v tomhle zařízení a na ostatní půjde, až budete online."],
      rejected: ["The order was not saved: a widget in it was removed from the catalog.",
        "Pořadí se neuložilo: jeden widget z něj byl odebrán z katalogu."],
      absent: ["Arranging is part of your own home screen, and a suggested layout has none.",
        "Uspořádání patří k vlastní ploše a navržené rozložení ho nemá."],
      withdrawn: ["Two widgets left the list with the modules that were withdrawn; the order of the rest is kept.",
        "Dva widgety odešly s odebranými moduly; pořadí ostatních zůstalo."],
      readonly: ["The household is read-only, so the order is shown and nothing can be dragged.",
        "Domácnost je jen pro čtení, takže pořadí vidíte, ale nepřetáhnete."]
    },
    "C-4": {
      empty: [["No household default is set.", "Six widgets that need no setup are a good first screen.", "Use the suggested six"],
              ["Výchozí rozložení domácnosti není nastavené.", "Šest widgetů, které nic nepotřebují, je dobrá první obrazovka.", "Použít navrženou šestku"]],
      pending: ["The default is saved here and reaches new members once this device syncs.",
        "Výchozí rozložení je uložené tady a k novým členům dorazí po synchronizaci."],
      rejected: ["The default was not saved: it contains a widget whose module is off for the household.",
        "Výchozí rozložení se neuložilo: obsahuje widget, jehož modul je v domácnosti vypnutý."],
      withdrawn: ["You set the household default until 9 September. What you set is still what new members get.",
        "Výchozí rozložení jste určovali do 9. září. To, co jste nastavili, noví členové pořád dostávají."],
      readonly: ["The household is read-only, so the default is shown and cannot be changed.",
        "Domácnost je jen pro čtení, takže výchozí rozložení vidíte, ale nezměníte."]
    },
    "C-6": {
      empty: [["Adam's home screen has nothing on it.", "The owner's default is four widgets he can then change.", "Use the household default"],
              ["Adamova plocha je prázdná.", "Výchozí rozložení od vlastníka jsou čtyři widgety, které pak může změnit.", "Použít výchozí rozložení"]],
      pending: ["Adam's changes are on his phone and reach the household at the next sync.",
        "Adamovy změny jsou v jeho telefonu a do domácnosti dorazí při příští synchronizaci."],
      rejected: ["The change was not saved: a child profile may not add a widget from a module it does not hold.",
        "Změna se neuložila: dětský profil nemůže přidat widget z modulu, který nemá."],
      absent: ["This layout is suggested rather than locked, so there is nothing here to unlock.",
        "Tohle rozložení je navržené, ne zamčené, takže tu není co odemykat."],
      withdrawn: ["One widget left when its module stopped being shared with Adam.",
        "Jeden widget odešel, když se jeho modul přestal s Adamem sdílet."],
      readonly: ["The household is read-only. Adam's widgets read and none of them acts.",
        "Domácnost je jen pro čtení. Adamovy widgety se čtou, žádný nejedná."]
    },
    "C-7": {
      empty: [["This locked layout has no widgets in it.", "An owner picks them; four is the usual number.", "Ask the owner"],
              ["V tomhle zamčeném rozložení nejsou žádné widgety.", "Vybírá je vlastník; obvykle jsou čtyři.", "Napsat vlastníkovi"]],
      absent: ["Arranging is not part of this app: on a locked layout the affordance is gone, not greyed out.",
        "Uspořádání tahle aplikace nemá: u zamčeného rozložení chybí, není zašedlé."],
      withdrawn: ["One widget left with the module that was withdrawn. The owner decides what replaces it.",
        "Jeden widget odešel s odebraným modulem. Čím se nahradí, rozhodne vlastník."]
    },
    "C-9": {
      empty: [["The frame has no widget in it.", "Every widget draws inside this shell — header, body, footer.", "See the catalog"],
              ["V rámu není žádný widget.", "Každý widget se kreslí uvnitř tohohle rámu — hlavička, tělo, patička.", "Zobrazit katalog"]],
      pending: ["The widget's own action is queued; the frame says so in its footer rather than in a dialog.",
        "Akce widgetu čeká ve frontě; rám to říká v patičce, ne v dialogu."],
      absent: ["A frame with no module behind it is not rendered at all, which is what this row documents.",
        "Rám bez modulu se vůbec nekreslí — právě to tenhle řádek dokládá."],
      withdrawn: ["The frame stays and says the module left, because a hole in the grid explains nothing.",
        "Rám zůstane a řekne, že modul odešel; díra v mřížce nevysvětlí nic."],
      readonly: ["The frame keeps its content and drops its actions, in every one of the three sizes.",
        "Rám si nechá obsah a zahodí akce, ve všech třech velikostech."]
    },
    "C-10": {
      empty: [["No widget keys are registered.", "Each module page registers its own — Chores registers three.", "Open a module page"],
              ["Není zaregistrovaný žádný klíč widgetu.", "Každý modul registruje své — Domácí práce tři.", "Otevřít stránku modulu"]],
      pending: ["Three of the twenty-four are showing a queued local write inside their own frame.",
        "Tři z dvaceti čtyř ukazují ve svém rámu čekající místní zápis."],
      absent: ["A key whose module a member does not hold is not offered here at all.",
        "Klíč modulu, který člen nemá, se tu vůbec nenabízí."],
      withdrawn: ["Four keys are shown as withdrawn rather than removed, so the count stays legible.",
        "Čtyři klíče jsou označené jako odebrané, ne smazané, aby počet zůstal čitelný."],
      readonly: ["Every one of the twenty-four is drawn with its actions absent.",
        "Všech dvacet čtyři je vykreslených bez akcí."]
    },
    "C-11": { absent: ["Reminders is not one of your modules, so nothing subscribes you to anything.",
      "Připomínky mezi vašimi moduly nejsou, takže vás nic nikam nepřihlašuje."] },
    "C-12": { absent: ["Writing your own reminder needs Reminders, which is not one of your modules.",
      "Vlastní připomínku napíšete v Připomínkách, a ty mezi vašimi moduly nejsou."] },
    "C-13": { pending: ["Your lead times are saved on this device and reach the server at the next sync.",
      "Nastavené předstihy jsou v tomhle zařízení a na server dorazí při příští synchronizaci."] },
    "C-15": { absent: ["Tasks is not one of your modules, so this board is not part of your app.",
      "Úkoly mezi vašimi moduly nejsou, takže tuhle nástěnku ve své aplikaci nemáte."] },
    "C-16": { absent: ["Card detail belongs to Tasks, which is not one of your modules.",
      "Detail karty patří k Úkolům, a ty mezi vašimi moduly nejsou."] },
    "C-18": { pending: ["The label is on the card already and reaches the board when this device syncs.",
      "Štítek je na kartě už teď a na nástěnku dorazí po synchronizaci zařízení."] },
    "C-20": { absent: ["Comments belong to Tasks, which is not one of your modules.",
      "Komentáře patří k Úkolům, a ty mezi vašimi moduly nejsou."] },
    "C-22": { pending: ["The column is usable here and reaches everybody else once you are online.",
      "Sloupec tu funguje hned a k ostatním se dostane, až budete online."] },
    "C-23": { absent: ["Notes is not one of your modules, so neither root is part of your app.",
      "Poznámky mezi vašimi moduly nejsou, takže ani jeden kořen ve své aplikaci nemáte."] },
    "C-24": { absent: ["This note lives in a root you cannot read, so the address opens nothing.",
      "Tahle poznámka je v kořeni, který nemůžete číst, takže adresa nic neotevře."] },
    "C-26": { withdrawn: ["Notes was shared with you until 9 September, so this search has nothing left to look in.",
      "Poznámky s vámi byly sdílené do 9. září, takže tohle hledání nemá kde hledat."] },
    "C-28": {
      conflicted: ["A file was moved in two places at once. Both destinations are kept until you pick.",
        "Soubor se přesunul na dvě místa zároveň. Obě cesty zůstávají, dokud si nevyberete."],
      absent: ["Documents is not one of your modules, so the tree is not part of your app.",
        "Dokumenty mezi vašimi moduly nejsou, takže strom ve své aplikaci nemáte."]
    },
    "C-29": { absent: ["Uploading needs contribute on Documents, and you hold view.",
      "K nahrání je potřeba oprávnění přispívat v Dokumentech; vy máte číst."] },
    "C-30": {
      empty: [["This document has no preview.", "A PDF shows its first page here; this type shows its details instead.", "Download the file"],
              ["Tenhle dokument nemá náhled.", "PDF tu ukáže první stranu; tenhle typ místo toho ukáže údaje.", "Stáhnout soubor"]],
      absent: ["The file is in a folder you cannot read, so its detail is not part of your app.",
        "Soubor je ve složce, kterou nemůžete číst, takže jeho detail ve své aplikaci nemáte."]
    },
    "C-32": {
      pending: ["The type and the expiry are saved here and reach the household at the next sync.",
        "Typ a platnost jsou uložené tady a do domácnosti dorazí při příští synchronizaci."],
      absent: ["A passport sits in a private folder, so it is not part of everybody's app.",
        "Pas je v soukromé složce, takže ho v aplikaci nemá každý."]
    },
    "C-33": { absent: ["Bulk actions need contribute on Documents, and you hold view.",
      "Hromadné akce vyžadují oprávnění přispívat v Dokumentech; vy máte číst."] },
    "C-34": {
      absent: ["The storage meter is the owner's screen, so it is not part of your app.",
        "Přehled úložiště je obrazovka vlastníka, takže ji ve své aplikaci nemáte."],
      withdrawn: ["You could see the household's storage until 9 September. Your own files are unaffected.",
        "Úložiště domácnosti jste viděli do 9. září. Vašich souborů se to netýká."]
    },
    "C-36": { absent: ["Chores is not one of your modules, so nothing here is assigned to you.",
      "Domácí práce mezi vašimi moduly nejsou, takže vám tu nic není přidělené."] },
    "C-37": {
      pending: ["What you ticked in the grid is here already and reaches the household at the next sync.",
        "Co jste v mřížce odškrtli, je tu hned a do domácnosti dorazí při příští synchronizaci."],
      absent: ["The weekly grid shows the whole household, which needs Chores — not one of your modules.",
        "Týdenní mřížka ukazuje celou domácnost a k tomu jsou potřeba Domácí práce, které nemáte."]
    },
    "C-38": {
      pending: ["Your edits to the definitions are saved here and go up when there is a connection.",
        "Úpravy definic jsou uložené tady a odejdou, jakmile bude připojení."],
      absent: ["Editing the definitions needs manage on Chores, and you hold contribute.",
        "Úprava definic vyžaduje oprávnění spravovat Domácí práce; vy máte přispívat."]
    },
    "C-39": { absent: ["This chore's editor needs manage on Chores, and you hold contribute.",
      "Editor téhle práce vyžaduje oprávnění spravovat Domácí práce; vy máte přispívat."] },
    "C-40": { absent: ["Points are Adam's own screen; nobody else's app has it.",
      "Body jsou Adamova obrazovka; v aplikaci nikoho jiného nejsou."] },
    "C-47": { withdrawn: ["The module this row belongs to stopped being shared with you, so the diff no longer opens.",
      "Modul, ke kterému řádek patří, se s vámi přestal sdílet, takže se rozdíl už neotevře."] },
    "C-49": {
      error: ["Household settings did not load. Nothing was changed — try again.",
        "Nastavení domácnosti se nenačetlo. Nic se nezměnilo, zkuste to znovu."],
      pending: ["The settings you changed are saved here and reach everybody at the next sync.",
        "Změněná nastavení jsou uložená tady a k ostatním dorazí při příští synchronizaci."],
      rejected: ["The change was refused: the household name must not be empty.",
        "Změna byla odmítnuta: název domácnosti nesmí být prázdný."],
      withdrawn: ["You could manage this household until 9 September. You are still a member of it.",
        "Domácnost jste mohli spravovat do 9. září. Členem jste pořád."]
    },
    "C-50": {
      empty: [["You are the only member.", "Inviting Petr takes his email and seventeen answers that are already filled in.", "Invite someone"],
              ["Jste tu jediný člen.", "K pozvání Petra stačí e-mail a sedmnáct odpovědí, které už jsou vyplněné.", "Pozvat někoho"]],
      withdrawn: ["You could see everybody's access until 9 September. Your own is on your account screen.",
        "Přístupy všech jste viděli do 9. září. Svůj najdete na obrazovce účtu."]
    },
    "C-51": {
      error: ["The module list did not load. Nothing was turned on or off — try again.",
        "Seznam modulů se nenačetl. Nic se nezaplo ani nevyplo, zkuste to znovu."],
      pending: ["The module you turned on works here already and reaches the household at the next sync.",
        "Zapnutý modul tu funguje hned a do domácnosti dorazí při příští synchronizaci."],
      rejected: ["Turning the module off was refused: it still holds data somebody else is using.",
        "Vypnutí modulu bylo odmítnuto: pořád v něm jsou data, která někdo používá."],
      withdrawn: ["You could turn modules on and off until 9 September. What is on stayed on.",
        "Moduly jste mohli zapínat a vypínat do 9. září. Co bylo zapnuté, zapnuté zůstalo."]
    },
    "C-54": {
      empty: [["Nothing is stored yet.", "The first photograph in Chat or Documents starts the meter.", "Add a file"],
              ["Zatím není uloženo nic.", "Měřidlo se rozjede první fotkou ve Zprávách nebo Dokumentech.", "Přidat soubor"]],
      absent: ["Storage against the allowance is the owner's screen, so it is not part of your app.",
        "Úložiště proti limitu je obrazovka vlastníka, takže ji ve své aplikaci nemáte."]
    },
    "C-56": {
      error: ["The data screen did not load. Nothing was exported, restricted or deleted.",
        "Obrazovka dat se nenačetla. Nic se nevyexportovalo, neomezilo ani nesmazalo."],
      absent: ["Export, restrict, hand over and delete are the owner's, so this screen is not part of your app.",
        "Export, omezení, předání i smazání patří vlastníkovi, takže tuhle obrazovku nemáte."],
      withdrawn: ["You could act on the household's data until 9 September. Your own rights are on your account.",
        "S daty domácnosti jste mohli nakládat do 9. září. Vaše vlastní práva jsou u účtu."]
    },
    "C-57": {
      error: ["The device list did not load. What each device has is unchanged.",
        "Seznam zařízení se nenačetl. To, co která zařízení mají, se nezměnilo."],
      absent: ["Clients and versions is the owner's screen, so it is not part of your app.",
        "Zařízení a verze jsou obrazovka vlastníka, takže ji ve své aplikaci nemáte."]
    },

    "D-6": { pending: ["The invoice you entered is saved on this device and reaches the household at the next sync.",
      "Zadaná faktura je uložená v zařízení a do domácnosti dorazí při příští synchronizaci."] },
    "D-48": { rejected: ["The copy was refused: the 2027 season already exists and copying would write over it.",
      "Kopie byla odmítnuta: sezóna 2027 už existuje a kopírování by ji přepsalo."] },
    "E-17": { conflicted: ["Two people set the interval at once — 12 months and 15 000 km. Both are kept until you pick.",
      "Dva lidé nastavili interval zároveň — 12 měsíců a 15 000 km. Obojí zůstává, dokud si nevyberete."] },
    "E-20": {
      rejected: ["The checklist was not saved: one item names a country profile this household does not use.",
        "Seznam se neuložil: jedna položka odkazuje na profil země, který tahle domácnost nepoužívá."],
      withdrawn: ["Property was shared with you until 9 September. The checklist stayed with the household.",
        "Nemovitost s vámi byla sdílená do 9. září. Seznam zůstal domácnosti."]
    },
    "E-22": { rejected: ["The location was not saved: the photograph is still uploading, and the row waits for it.",
      "Umístění se neuložilo: fotka se pořád nahrává a řádek na ni čeká."] },
    "E-40": { withdrawn: ["Chat was shared with you until 9 September, so what it uses is no longer itemised for you.",
      "Zprávy s vámi byly sdílené do 9. září, takže jejich obsazení už nevidíte po položkách."] },
    "E-42": { rejected: ["The search was refused: it reached a conversation you are no longer in.",
      "Hledání bylo odmítnuto: sáhlo do konverzace, ve které už nejste."] },
    "F-3": { pending: ["Three rows here are local writes waiting to go up. Every one of them is still editable.",
      "Tři řádky jsou místní zápisy čekající na odeslání. Všechny jdou pořád upravit."] },
    "F-5": { conflicted: ["Six things are waiting for an answer. Nothing here resolves itself and nothing ages out.",
      "Šest věcí čeká na odpověď. Nic se tu nevyřeší samo a nic nevyprší."] },
    "F-15": {
      pending: ["Your order is already what this device shows and reaches the others at the next sync.",
        "Vaše pořadí tohle zařízení ukazuje hned; na ostatní dorazí při příští synchronizaci."],
      absent: ["Arranging needs at least view on one module, and you hold none in this household.",
        "K uspořádání je potřeba mít aspoň čtení u jednoho modulu; v téhle domácnosti nemáte žádný."]
    },
    "F-20": {
      error: ["Your notification settings did not load. What you are told about has not changed.",
        "Nastavení oznámení se nenačetlo. To, o čem vás informujeme, se nezměnilo."],
      pending: ["The category you switched is saved here and reaches the server at the next sync.",
        "Přepnutá kategorie je uložená tady a na server dorazí při příští synchronizaci."],
      rejected: ["The change was refused: the household turned this category off for everybody.",
        "Změna byla odmítnuta: domácnost tuhle kategorii vypnula všem."],
      absent: ["Notifications are per person and per device, so a locked child profile does not have this screen.",
        "Oznámení jsou na člověka a na zařízení, takže zamčený dětský profil tuhle obrazovku nemá."]
    }
  };

  window.HH_COPY = {
    version: "0.1-stage-23",
    titles: T, ledes: L, states: SS,

    title: function (row, locale) {
      if (!row) return "";
      var t = T[row.id];
      if (!t) return row.title;
      return (locale === "cs" ? t[0] : locale === "de" ? t[1] : row.title) || row.title;
    },
    lede: function (row, locale) {
      if (!row) return "";
      if (locale === "cs" && L[row.id]) return L[row.id];
      return row.lede;
    },
    /* the screen's own words for a state, in the rail's language, English where
       Czech is not authored — never the shell's generic wording */
    state: function (id, key, locale) {
      var e = SS[id] && SS[id][key];
      if (!e) return null;
      if (key === "empty") {
        var pick = locale === "cs" && e[1] ? e[1] : e[0];
        return { s: pick[0], e: pick[1], a: pick[2] };
      }
      return (locale === "cs" && e[1]) ? e[1] : e[0];
    },

    /* What is authored and what is not, counted rather than claimed. */
    coverage: function (rows) {
      var n = { screens: 0, csTitle: 0, deTitle: 0, csLede: 0, enLede: 0, stateSlots: 0 };
      (rows || []).forEach(function (r) {
        n.screens++;
        if (T[r.id]) { n.csTitle++; n.deTitle++; }
        if (r.lede) { n.enLede++; if (L[r.id] || /[ěščřžýáíéůúňťď]/i.test(r.lede)) n.csLede++; }
      });
      Object.keys(SS).forEach(function (id) { n.stateSlots += Object.keys(SS[id]).length; });
      return n;
    }
  };
})();
